---
title: Nodewaste
baseurl: "/"
permalink: "/:title/"
palette: blue
header:
  title: Nodewaste
  logo_img: "/images/logo (2)@4x.png"
  has_nav: true
  menu:
    actions:
    - label: Sign Up
      url: "/signup"
footer:
  logo_img: "/images/Artboard 1xxhdpi.png"
  tagline: Nodewaste by Supercompute
  has_nav: true
  nav_title: Company
  has_social: true
  social_title: Community
  has_subscribe: true
  subscribe_title: Subscribe
  subscribe_content: Stay up to date with our latest developments.
  content: "&copy; Stackbit. All rights reserved."
  links:
  - new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
collections:
  posts:
    permalink: "/posts/:title/"
